### ISSUE TITLE
kanagawa highlight color

### ISSUE THREAD

**Issue by Musab-Nazir** [konrad1977/emacs#3]
Hi
First off just wanted to say thanks for creating the kanagawa theme (I use it for nvim and love it). I'm pretty new to emacs to just trying to learn how to adjust it to my liking. 

I'm not sure what that section of the window is called but when I press `M-x` I notice the theme doesn't highlight the entire line which ends up creating this weird box like shape. I notice other themes don't do this (attached an example of `doom-miramare`), so I just wanted to ask if you could point me to where I need to modify the theme file if I want kanagawa to behave like miramare in this case. Hope I explained my issue correctly.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/35812595/167672873-7815712d-54b7-470b-bf89-c1f533c1b7cd.png">
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/35812595/167673626-5cebcfd8-0efa-421d-bf9e-23bd67339c0b.png">

**Comment by Musab-Nazir** [comment]
I found it through trial and error. The variable is called `shadow` under the `;; Customize Faces` section of the theme. Commenting it out gets me what I was after

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/35812595/168111990-eebea8cc-2b2e-4d2e-b27b-b6b01c779ce7.png">

**Comment by konrad1977** [comment]
Thanks. I think I recently fixed this in catppuccin theme, but probably forgot to fix in Kanagawa.
