### ISSUE TITLE
ivy-posframe face in kanagawa theme causing unreadable UI

### ISSUE THREAD

**Issue by HeyParkerJ** [konrad1977/emacs#4]
Hi, firstly thank you so much for making this theme! It's the first one I've seen in a few years that got me really excited to have discovered and use it!

I did run into one hiccup during usage that I have finally figured out enough to write to you about it, and that's that my ivy-posframe would be completely unreadable on initial load of Emacs, due to what I believe is the ivy-posframe setting [here](https://github.com/konrad1977/emacs/blob/main/themes/kanagawa-theme.el#L307). I'll attach some screenshots.

One thing I do not understand, is that by running `M-x load-theme` with kanagawa after Emacs finished loading would fix this issue, so I'm not entirely sure if this is an issue with the theme itself, or my own setup.

This is the frame on initial load
![Screen Shot 2022-09-06 at 12 35 54 PM](https://user-images.githubusercontent.com/11808813/188716811-d58d2b15-1fe7-4fc5-9b42-30dd57d79bd8.png)

This is after reloading kanagawa with `M-x load-theme`
![Screen Shot 2022-09-06 at 12 36 02 PM](https://user-images.githubusercontent.com/11808813/188716816-effc3c08-a016-4550-a7d5-b3476f5e0194.png)

This is after commenting out L307 linked above.
![Screen Shot 2022-09-06 at 12 54 16 PM](https://user-images.githubusercontent.com/11808813/188716821-e12b0b63-09b3-405d-a38e-e560ca8e97da.png)

If this isn't replicatable, obviously feel free to close this issue as it must be something on my end, but I wanted to at least document this in case I'm not the only one to run into the problem.

Thank you again! Truly do love this theme (enough for me to learn a bit about theming and how I could fix this issue!)

**Comment by konrad1977** [comment]
I need to look into this. I am not using ivy anymore (consult/vertico) now. But I have to make sure it works for all completion frameworks. Thanks for reporting.

**Comment by konrad1977** [comment]
The reason it works after you loading the theme again with `load-theme` is that posframe doesnt load correctly, it must be done during startup (or atleast I had the same problem with teams and pos frames).

**Comment by konrad1977** [comment]
@HeyParkerJ I updated the theme let me know if it works. 

I added catppuccin-mocha/frappe/machiato themes which you might like to.
