### ISSUE TITLE
Have you thought above getting your Kanagawa theme on MELPA ? / Separate repository ? (Suggestion)

### ISSUE THREAD

**Issue by Saladin1812** [konrad1977/emacs#5]
I see that you have worked on creating the kanagawa theme and on reddit there were talks about getting this on melpa 

https://github.com/jasonm23/emacs-theme-kanagawa/blob/master/kanagawa-theme.el
This doesn't seem to be getting updated.. 

Also will be great if you create a repo specifically for the kanagawa theme.. so people can install it simply by using the username/package-name.

example - 
```
(package! kanagawa-theme :recipe
(:host github :repo "konrad1977/kanagawa-theme" :branch "master")) 
```

I am currently using it and loving it.. also compared it to the original work of reblot's nvim theme.. :)

**Comment by konrad1977** [comment]
I have never put anything on Melpa. Maybe I can look into it. Thanks!

**Comment by konrad1977** [comment]
It now lives in its own repo:
https://github.com/konrad1977/kanagawa-emacs
https://github.com/konrad1977/oxocarbon-emacs
https://github.com/konrad1977/pinerose-emacs

**Comment by Saladin1812** [comment]
great :+1:
