### ISSUE TITLE
Avoid `curl` in welcome.el

### ISSUE THREAD

**Issue by skx** [konrad1977/emacs#7]
You could instead use `url-copy-file`, or similar, to avoid the external dependency.

Other approach:

* https://www.gnu.org/software/emacs/manual/html_node/url/Retrieving-URLs.html

**Comment by konrad1977** [comment]
I updated the fetch weather data. It's async now so it starts up even faster. Thanks for the great suggestion.

**Comment by skx** [comment]
Closed in d13b83e2802d17081ec139e5fb3c59d08482a1ab
